### ISSUE TITLE
Navigate within the same doc?

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/CommentLinks#15]
From https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks&ssr=false#qna

> Is there any way to do put a link in the top of a file that points to a later place in the file using text, not line numbers? I have a DiskTheory.txt file this begins with various text data. At the end I want to put a the text tags that I will use for links I will point to by numbered strings CDT01, CDT02..., from elsewhere. That works fine, But if I add link:DiskTheory.txt:CDT01 at the top of DiskTheory.txt then clicking it will find itself as the first occurrence of string "CDT01" and not the "CDT01" later in the file. It finds the first occurrence of the string and understandably so. Feature creep warning: What if the code skips text if it is inside a "link:" string so it will go to the next one? I looked at your code (not a c# programmer) but I think you could tweak GetLineNumber to change "if (line.Contains(content))" to "if (line.Contains(content) && !line.Contains("link:"))" or something.

**Comment by mrlacey** [comment]
How much would this provide beyond the 'Find in File' functionality already built into the Visual Studio Editor?
For instance, if I'm looking for multiple instances of text throughout a document, I can highlight one instance, press `ctrl+F`, then all instances are highlighted and I can easily navigate between them.

**Comment by mrlacey** [comment]
From the example in the OP, it's not clear which of the following scenarios are desired.

1. Have links at the top of a document that can link to arbitrary locations later in the same document. (An in-document Table of contents)
2. Have links to other documents that also include "table of contents" links.

If just option 1, this could be done by adding support for links without a file name (e.g. `link::CDT01`, `#link::~:text=CDT01` or `link:#L300`) that would automatically be applied to the same document and start searching from the end of the found link location.

Alternatively, Option 1 could be done with a different keyword (rather than `link:`) to indicate the term to search for. (maybe `find:CDT01`)

If do option 2, would need to do the search, as per the OP, where look for the first instance of the defined text that isn't immediately preceded by `link:`

**Comment by markyoung143** [comment]
I think option 1 is desired. The functionality consists of a link: statement and target location it is supposed to goto. I'm saying the target location should not be "inside" another link: statement. If this line would be excluded as a possible target, then a link at a top of a file to somewhere farther in the file would work. If someone really wanted to point to line with a link: in it, it seems to be he would be asking the user to click twice for no reason?

**Comment by mrlacey** [comment]
I've implemented a version of option 1 above where a file name is required but if it's the same as the open document it will search further down in that same document.
