### ISSUE TITLE
Support adding space after initial colon

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#2]
i.e. currently this registers:
```cs
// link:file.js
```

but this does not:
```cs
// Link: file.js
```

I guess it was my initial instinct to format the comment like I would a `TODO:` vs. a URL in a way. Having that flexibility would be handy, at least for initial discovery of the feature too.

**Comment by mrlacey** [comment]
This functionality is included in v1.1 which is now available.
