### ISSUE TITLE
Make link identifier customizable

### ISSUE THREAD

**Issue by DanielMorsch** [mrlacey/CommentLinks#22]
Hi,
it would be nice if the link identifier could be customizable. So that you could also use other prefixes. 
For example "see:" or "file:"

**Comment by mrlacey** [comment]
Nice idea.

For your scenario(s), does it need to be able to work with multiple prefixes/indicator words or just one?

**Comment by DanielMorsch** [comment]
At the moment I only use the one " file:" prefix.

**Comment by mrlacey** [comment]
WIP:

![image](https://user-images.githubusercontent.com/189547/109524789-cdc0ef80-7aa8-11eb-840f-89d7d4681e27.png)

**Comment by mrlacey** [comment]
This has some implications on extension loading that I'm still investigating.

**Comment by mrlacey** [comment]
This has now been released as part of version 2.3.
If you find this useful, please leave a review or rating at https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks&ssr=false#review-details
