### ISSUE TITLE
Ver 2.2 fixed case where a link in a file points to a later line in the same file. It seems version 2.3 broke that?

### ISSUE THREAD

**Issue by markyoung143** [mrlacey/CommentLinks#26]

**Comment by markyoung143** [comment]
Line1 of DiskTheory.txt
whatever
link:DiskTheory.txt:CDT01
... { various lines }
CDT01: Blah blah blah
The goal is to have a link on line 3 above that points the the preceding line and that link works from both inside and outside this file. The solution was that the code that searches for a target string must ignore (not stop on) an string that is "inside" a link command. Ver 2.1 links line line 3 will goto line 3 not the "CDT01: Blah blah blah" line later in the same file

**Comment by markyoung143** [comment]
I could not try ver 2.2 again because I did not save it when 2.3 came out and I can't see a way to get 2.2 from the Download link - just the latest. Next time I will save the previous version with a version number in case I want to try an old version.

**Comment by mrlacey** [comment]
Yes, 2.3 broke this feature. It still works with miscellaneous files but not those that are part of a project.

**Comment by mrlacey** [comment]
version 2.4 includes a fix for this issue and has been submitted to the marketplace. It should be available shortly.
