### ISSUE TITLE
Get exception in VS2017 with CommentLink 2.3 opening CommentLinksFeatureRequest.txt 

### ISSUE THREAD

**Issue by markyoung143** [mrlacey/CommentLinks#27]
[CommentLinksFeatureRequest.txt](https://github.com/mrlacey/CommentLinks/files/6135280/CommentLinksFeatureRequest.txt)

[ActivityLog.zip](https://github.com/mrlacey/CommentLinks/files/6135292/ActivityLog.zip)
![image](https://user-images.githubusercontent.com/16338715/111039863-f96f9e00-83f5-11eb-91b8-bf1dfe182613.png)

**Comment by markyoung143** [comment]
Happens every time, even if I open VS with not files and just open this one file

**Comment by mrlacey** [comment]
Does it happen when you click on any particular link to open this file? Or is it a link within `CommentLinksFeatureRequest.txt` that causes the error?

**Comment by mrlacey** [comment]
> Does it happen when you click on any particular link to open this file? Or is it a link within `CommentLinksFeatureRequest.txt` that causes the error?

Never mind, It happens when opening the file. ;)

**Comment by mrlacey** [comment]
version 2.4 includes a fix for this issue and has been submitted to the marketplace. It should be available shortly.
