### ISSUE TITLE
Two Links on the same line.

### ISSUE THREAD

**Issue by DanielMorsch** [mrlacey/CommentLinks#29]
Hi,

sometimes we have links on the same comment line.
Currently, only the first one is detected and the button is displayed.

Like this one:
`// (cf. file:"file1.ext" and file:"file2.ext" )`

Maybe it would be possible to adjust the search of the trigger words a bit.

**Comment by mrlacey** [comment]
I'll have a look and see how easy this will be.
It's definitely going to get complicated when dealing with text that comes after the file name and is used for search.

As a temporary workaround, you could (as I'm sure you're already aware) refactor the comment over multiple lines

e.g.

```cs
// crossref. file:"file1.ext"
//  and file:"file2.ext" 
```

or even do that temporarily to have the button be shown so you can click to navigate

**Comment by mrlacey** [comment]
The ability to have multiple links in a single line has been **added to version 2.5.1** which is now [available from the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks).

example:
![image](https://user-images.githubusercontent.com/189547/112630636-ca155400-8e2d-11eb-9d1e-f38bde512bae.png)


If you find this extension useful a rating and review in the marketplace will be greatly appreciated: https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks&ssr=false#review-details
Positive reviews encourage me to keep working on this tool and help others see this as something they can trust and may find useful

**Comment by DanielMorsch** [comment]
Really nice. Thank you. Works very well.
