### ISSUE TITLE
No feedback provided if link is invalid

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#3]
If I try and link to a file which doesn't exist (typo) or to text which doesn't exist in the file:

```cs
// link:filexists.cs:badtext
```

Then no indication is provided to me when I click that something is wrong. Could be handy if the link is invalid when clicked the icon turns red and becomes unclickable until the text is updated?

**Comment by mrlacey** [comment]
Now indicating files that can't be found

![image](https://user-images.githubusercontent.com/189547/79003455-8fe27200-7b4a-11ea-81ea-25d6a45bd55c.png)

If the line number doesn't exist.

![image](https://user-images.githubusercontent.com/189547/79003815-434b6680-7b4b-11ea-954c-62a514503516.png)

![image](https://user-images.githubusercontent.com/189547/79003792-34fd4a80-7b4b-11ea-8a7b-ec5dbd9d8db6.png)

If the text can't be found

![image](https://user-images.githubusercontent.com/189547/79003919-8e657980-7b4b-11ea-9fe5-3241f9240d27.png)

![image](https://user-images.githubusercontent.com/189547/79004044-d71d3280-7b4b-11ea-8719-d6eadb23ad01.png)

**Comment by mrlacey** [comment]
This functionality is included in v1.1 which is now available.
