### ISSUE TITLE
Add Support for VS 2022

### ISSUE THREAD

**Issue by DanielMorsch** [mrlacey/CommentLinks#33]
Hi,

It would be helpful if the extension was also available for Visual Studio 2022.

Currently it is not yet part of the daily work, but I think it could be soon, if the other extensions (Resharper, etc.) also support the new VisualStudio.

**Comment by mrlacey** [comment]
It's on my list (currently migrating multiple extensions based on what's being asked for most)
I expect this to be done in the next few weeks.

**Comment by DanielMorsch** [comment]
Thank you.  I'm glad to hear that.

**Comment by mrlacey** [comment]
V2.8 is now available and supports VS2022

---

If you have any problems, comments, or suggestions: please [raise an issue](https://github.com/mrlacey/CommentLinks/issues/new).
If you love it, please leave a [rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks&ssr=false#review-details) and consider [sponsorship](https://github.com/sponsors/mrlacey) 😄
