### ISSUE TITLE
Issues with navigating `.vscode` directory?

### ISSUE THREAD

**Issue by michael-hawker** [mrlacey/CommentLinks#38]
Trying to link to a config file that's in the `.vscode` directory (though from a `.github` directory, so maybe it's on the other side).

In either case, it's not behaving as expected.

Folder structure within repo:
 - .github/workflows/build.yml (where I'm putting link)
 - .vscode/launch.json (where I want to link to)

Note, none of these files are in my current open solution (though the solution is at the root of this folder structure).

This is what I tried:

1) I started with `// LINK: ./.vscode/launch.json` (to mean from repo root)

2) I tried just `.vscode/launch.json` as well.

Both the original and this next one instead opened up some internal vs file: `C:\Users\username\AppData\Local\Microsoft\VisualStudio\17.0_f650100f\JSPS\launchJson_schema.json` instead?

3) Then I tried `../../.vscode/launch.json` thinking the relative path should work directly, but that said it was unable to find the file.

Not sure what to try next.

**Comment by mrlacey** [comment]
When I try the above (option 2 specifically) I get the correct file opened. (see below)

![image](https://user-images.githubusercontent.com/189547/168480686-bc6fdb9a-45dd-406d-ac3e-91c96035b3cb.png)

Note that the path `C:\Users\matt\AppData\Local\Microsoft\VisualStudio\17.0_7f04548fExp\JSPS\launchJson_schema.json` is not the path of the document opened, it is the schema that the editor is using to validate the JSON. 
It does open the correct file.

@michael-hawker  Is this what you were seeing?

**Comment by michael-hawker** [comment]
Ah, maybe I was super confused by the json schema path being shown and the extra whitespace... I'll check again. Thinking back, it may have been doing the right thing. Just a very odd path to be exposed in the UI, but it's probably been a while since I opened a json file in VS.

**Comment by michael-hawker** [comment]
Alright, I was confused about the file it opened. And the direct relative path between the files `../../.vscode/launch.json` is indeed working.

However, none of the things I originally tried worked:
- .vscode/launch.json
- ./.vscode/launch.json
- /.vscode/launch.json

I suppose the relative path is going to be fine here, but wondering if there's a way to specify from the project/repo root that I'm missing?

**Comment by mrlacey** [comment]
> Alright, I was confused about the file it opened. And the direct relative path between the files `../../.vscode/launch.json` is indeed working.
> 
> However, none of the things I originally tried worked:
> 
> * .vscode/launch.json
> * ./.vscode/launch.json
> * /.vscode/launch.json
> 
> I suppose the relative path is going to be fine here, but wondering if there's a way to specify from the project/repo root that I'm missing?

I've revisited this and think I now better understand what you're asking.
The reason the things you originally tried didn't work is that the extension knows nothing about solutions, repositories, or anything beyond plain text (which is how it treats all files) and the file system. (And running commands if you want to get picky.) 

If you really wanted to be able to navigate based on your examples and the use of relative paths is insufficient, we could add something like the following ideas:

`link: [REPOROOT].vscode/launch.json` 
This would use `[REPOROOT]` as an indicator to find the root of the currently open repository and search from there.
A possible downside to this is that `[REPOROOT]` may not always be understood or available.

or 

`link: .../.vsroot/launch.json`
This would use a triple dot/period as an indicator to keep searching up the directory structure (from the location of the current file) until the specified path could be resolved.
A possible downside to this is that it may be easy to misread `...` as `..` and so expect it to point to somewhere else.

Are either of these appealing?

**Comment by michael-hawker** [comment]
I think it'd only make sense to introduce something like `[REPOROOT]` if there were other anchors to use as well vs. one-off.

I like the `...` or maybe four dots to reduce accidental overlap and make it more apparent?

`link: ..../.vsroot/launch.json`

Other option is to do something like MSBuild does with wildcards (though not sure if they're generally supposed to be rooted somewhere):

`link: **/.vsroot/launch.json`

**Comment by mrlacey** [comment]
> Other option is to do something like MSBuild does with wildcards (though not sure if they're generally supposed to be rooted somewhere):
> 
> `link: **/.vsroot/launch.json`

Using `**` is a nice idea but this already has a special meaning within paths (not just msbuild) and that is in searching forward any number of directories. This is the opposite of what we want here as we want to search towards the drive root, not away from it.

How about using any number of consecutive dots (but at least 3) to indicate searching back towards the drive root to find the path? This way if anyone feels 4 or 5 (or more) dots is a better way to avoid accidentally misreading the intention they can use that.

**Comment by mrlacey** [comment]
I've just released v2.13 to add this functionality. Let me know if it doesn't do everything you were after.
