### ISSUE TITLE
Provide context menu helpers to quickly generate links?

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#4]
It could be handy when having a selection of text in a file, to be able to go to the context menu and copy text in the form of a formatted link that'll take me to that location (similarly for a line).

E.g. in a 'MyFunction.cs` file:

```cs
9
10     public void MyFunction() {
11     //
12     }
```

If I right-click with `MyFunction` text selected could be a 'Comment Links` sub-menu with the options:
 - Copy Link to this Line ( link:MyFunction.cs#L10 )
 - Copy Link to text 'MyFunction' ( link:MyFunction.cs:MyFunction )
 - Copy Link to file ( link:MyFunction.cs )

The `link:` prefix could be an option in the settings in case folks want it as `LINK:` or `Link: ` etc...

Could also be handy for cases where if there are multiple same named files in the solution that the copy function would add parent directories to the link until it's unambiguous.

**Comment by mrlacey** [comment]
I can see the value in this.
It won't be in v1.1 but expect this to come "soon"

**Comment by mrlacey** [comment]
Coming in v1.2

![image](https://user-images.githubusercontent.com/189547/79244664-12cb3b80-7e6f-11ea-8761-51cd366d2bd2.png)

with simple configuration

![image](https://user-images.githubusercontent.com/189547/79245436-ff6ca000-7e6f-11ea-9f50-73988a34755d.png)


"link", "Link", or "LINK" are configurable

boolean option for including the relative path or not. Trying to work out if a local path is ambiguous is more than I can manage at the moment. (It's also very slow 😢)

**Comment by mrlacey** [comment]
This new functionality is included in version 1.2 which is now available from the marketplace.
