### ISSUE TITLE
Right click menu - "(Add) Comment Link to this"

### ISSUE THREAD

**Issue by ponnchamy** [mrlacey/CommentLinks#40]
Thank you Matt for this unique idea and all your work in this for making our work easier.

To add a new link, I request you to add a context menu - "Comment Link to this"

When we right-click on a function name and use this menu, it should create a comment link in clipboard, that we can paste anywhere to jump to this location/function.

Example: 
// Link:Example.cpp:"void ExampleFunction"
//right click on the below function name and click "Comment Link to this" to create the above line in clipboard
void ExampleFunction(int test) 
{
    return;
}

This will save a lot of time and prevent typo error.

Thanks again
Ponnuchamy
FlexiMusic

**Comment by mrlacey** [comment]
Does the existing `Copy link to Selection` functionality not already do this?

- Select some text (could be a function name)
- Right Click
- Comment Links > Copy link to Selection
- See something like `link:MainViewModel.cs:OnTemplatesAvailableAsync` is in the clipboard

![image](https://user-images.githubusercontent.com/189547/169716222-fad1d81c-5c9b-46a4-98c3-73559ede0877.png)

**Comment by ponnchamy** [comment]
Good.
Yes, it is already there and it is working.
I find it only after seeing your reply.

Please mention this info in the document (in CommentLinks's first page in marketplace.visualstudio and in github).

I see, it copies link like this: link:Example.cpp:void%20ExampleFunctionName()
Instead, it can be like this (more readable): Link:Example.cpp:"void ExampleFunctionName()"

Regards
Ponnuchamy
FlexiMusic
