### ISSUE TITLE
[Feature Request] Shortcut for In-file links

### ISSUE THREAD

**Issue by holeow** [mrlacey/CommentLinks#42]
Would it be possible to ease the way to create links that targets a position within the same file?

Something like link:this#L25, or even  link:#L25 / link::"My text"

**Comment by mrlacey** [comment]
X-Ref #37

**Comment by mrlacey** [comment]
@holeow out of curiosity:
- Are you using a combination of links within the same file and links between files?
- What file types are you using this with?
- Do you want to be able to link to things above and/or below the link?
- Do you have situations where you might want to create something like `link::"my text"` where "my text" may appear multiple times within the file?

**Comment by mrlacey** [comment]
v2.11 has just been published to the marketplace and includes the ability to use shortcuts for navigating within the same file that works like this:

- Add support for `link:^:"search term"` as a way to go (within the same file) to the nearest instance of the search term above the line with the link
- Add support for `link:v:"search term"` as a way to go (within the same file) to the nearest instance of the search term below the line with the link

Please let me know how you get on with this version.
