### ISSUE TITLE
Comment Links context menu not showing up in XAML files

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#48]
VS 17.4.2

![image](https://user-images.githubusercontent.com/8959496/205434553-256aad51-4bb1-4048-ab50-4c949f87e01a.png)

The Comment Links sub-menu is missing?

**Comment by mrlacey** [comment]
Yes. It's not showing up for XAML files. :(
It does show for other file types though.

**Comment by mrlacey** [comment]
Oh yes. XAML files aren't considered `code` in the Visual Studio file type hierarchy.

**Comment by mrlacey** [comment]
Version 2.14 is now in the marketplace and should fix this issue. Let me know if you find any more issues.
