### ISSUE TITLE
Feature request: Hide link after "// Link: ...."

### ISSUE THREAD

**Issue by hals1010** [mrlacey/CommentLinks#49]
Would be nice to have an option to hide the "explicit" link information, so something like:

// [->] Link: ...

vs

// [->] Link: C:\Data\SourceCode\Cpp\DatabaseClient.cpp:CreateDatabase

Best,
Jörn

**Comment by mrlacey** [comment]
Is there any more to this than it would be nice?
Is the path distracting?
Is it an issue because the paths are long?
Something else?

I just want to understand. :)

**Comment by hals1010** [comment]
Here's a screenshot of one of my headers:

![Header](https://user-images.githubusercontent.com/22933506/214333511-f8417679-42a1-4f10-adc9-221808657261.png)

I use your "// Link:" to a) see whether a function has an associated unit-test, and b) to quickly jump to it. If you compare it with the bookmark on the left hand side, you'll probably agree that the latter is more subtle.

So, I thought it would just be "nice to have". Can I live without it? Most probably yes ;)

**Comment by mrlacey** [comment]
Seems reasonable. 
I work mostly in C# and VS has tooling for that to point to related unit tests so I've not had to manually add links to related tests.
Thanks for helping me understand how this could help.

**Comment by mrlacey** [comment]
I can't work out how to do this :(

Also, it raises possible usability issues around how to view and edit the text that is being hidden.

**Comment by hals1010** [comment]
Nevermind Matt, thanks for looking into this.

(after using your plugin for a while, I got used to the "long" comments)

**Comment by mrlacey** [comment]
This was requested again, but I'm going to close it because:

1. I can't work out how to do it.
2. It raises a challenge of how to show and hide the hidden text so it can be viewed and edited.
