### ISSUE TITLE
How to modify the icon?

### ISSUE THREAD

**Issue by derricck** [mrlacey/CommentLinks#51]
I modified both the .ico and .png and recompiled the extension, but it continued with the same icon: ![CommentLinksIcon](https://user-images.githubusercontent.com/105561748/227223237-4e8eba79-2069-400d-91b4-7a3252994531.png)

![image](https://user-images.githubusercontent.com/105561748/227222894-5a4490ee-7263-4c93-9ceb-afa7dceb7b3d.png)

Is the link icon loaded by any base64 string or I'm missing something?

**Comment by derricck** [comment]
I just changed the icon, but i figured out that its not really an icon, its a Unicode character: https://github.com/mrlacey/CommentLinks/blob/7c354aeee790101ee5448713da3cbad0104234ec/src/CommentLinkAdornment.cs#L26

I have experience only with `c++`, i have modified the function as:
```c#
        internal CommentLinkAdornment(CommentLinkTag tag, int currentLineNumber)
        {
            this.Content = new TextBlock { Text = "📌" };
            this.Foreground = new SolidColorBrush(Color.FromRgb(71, 165, 10));
            this.BorderBrush = null;
            this.Padding = new Thickness(0);
            this.Margin = new Thickness(0);
            this.Background = Brushes.Transparent;
            this.Cursor = Cursors.Hand;
            this.CmntLinkTag = tag;
            this.currentLineNumber = currentLineNumber;

            // Add event handlers
            this.MouseEnter += this.CommentLinkAdornment_MouseEnter;
            this.MouseLeave += this.CommentLinkAdornment_MouseLeave;
        }

        private void CommentLinkAdornment_MouseEnter(object sender, MouseEventArgs e)
        {
            // Set the background color to a semi-transparent version of the current color
            this.Background = Brushes.Transparent;

            // Set the content color to a different color
            ((TextBlock)this.Content).Foreground = new SolidColorBrush(Color.FromRgb(71, 165, 10));
        }

        private void CommentLinkAdornment_MouseLeave(object sender, MouseEventArgs e)
        {
            // Set the background color to a semi-transparent version of the current color
            this.Background = Brushes.Transparent;

            // Set the content color to a different color
            ((TextBlock)this.Content).Foreground = new SolidColorBrush(Color.FromRgb(71, 165, 10));
        }
```

But the "icon" still get highlighted when the mouse is over it.
Do you know how I could remove the highlight?

![devenv_2023-03-23_11-18-25](https://user-images.githubusercontent.com/105561748/227236342-6930b967-5e6b-4edf-aaa1-c4328fdd0ec0.png)

![devenv_2023-03-23_11-18-28](https://user-images.githubusercontent.com/105561748/227236318-46fe92f1-4e3f-4cc8-823d-3d2b1e8996ed.png)

**Comment by mrlacey** [comment]
The behavior you're seeing is because the control is actually a button and that is the default behavior for a button. 
You'll need to retemplate it to remove this behavior. Although it's not good practice to remove indication that something is clickable when the cursor is over it.

**Comment by derricck** [comment]
I modified the trigger word to:
```c#
 public string TriggerWord { get; set; } = "#";
 ```
As it didn't conflict with the regex you've set.

My attempt was to make it more 'clean' possible, i also tried removing the `.Content` `TextBlock`:
```c#
this.Content = new TextBlock { Text = "➡" }; 
```
So i could set the trigger word to `📌` and also could get rid of the `#`
![image](https://user-images.githubusercontent.com/105561748/227507188-d380dcda-940d-4bc3-a687-7f6d2b1116b4.png)

But it uses the `.Content` to render the button so i got lost

**Comment by mrlacey** [comment]
There's now built-in support for changing the icon as of version 3.0 (in the marketplace now).
