### ISSUE TITLE
Question: Possibility to implement links in tooltip and quoting the linked block

### ISSUE THREAD

**Issue by skhrshin** [mrlacey/CommentLinks#54]
## Question overview

In the editor window, a tooltip appears when the mouse cursor points at an identifier. The tooltip shows the comment written above the definition of the identifier. So, my question is if it is possible to implement features satisfying the following behaviors:

- When you write a link in the comment above the definition, the tooltip shows not just the plain text "link:..." but an anchor or a link button.
- New "link:file:begin:end" syntax which represents a block of code is introduced.
- When the tooltip shows a link to a block, it also quotes the actual source code within the block.

## Reason of question

I'm using Boost C++ Library and often write a function which returns `boost::iterator_range`. If the return type is simple, the tooltip is very useful because the type of elements within the range is also shown like `boost::iterator_range<const int *>`. But I also often combine `boost::iterator_range` with `boost::transform_iterator` which transforms the element into another type.

```cpp
#include <vector>
#include <boost/iterator/transform_iterator.hpp>
#include <boost/range/iterator_range.hpp>

auto convert_int_vector_to_float_collection(const std::vector<int>& in) {
    auto to_float = [](int elem) {
        return static_cast<float> (elem);
    };
    return boost::make_iterator_range(
            boost::make_transform_iterator(in.begin(), to_float),
            boost::make_transform_iterator(in.end(), to_float));
}
```

In that case, the tooltip is complex and it is not easy to understand the type of transformed elements. The easiest solution to this problem is to write a comment.

```cpp
/// <returns>Seqeuence of float</returns>
auto convert_int_vector_to_float_collection(const std::vector<int>& in) {
```

But comment is just a text, so there is no validation which makes sure that the written specification is actually correct. What the second time I tried to do was to use `<see>`(https://learn.microsoft.com/en-us/cpp/build/reference/see-visual-cpp?view=msvc-170) and `static_assert`.

```cpp
#include <type_traits>
#include <utility>
...

/// <see cref="assertions"/>
auto convert_int_vector_to_float_collection(const std::vector<int>& in) {
    ...
}

namespace assertions {

static_assert (std::is_same_v<
                   decltype (convert_int_vector_to_float_collection(
                                     std::declval<std::vector<int>>())
                             .front()),
                   float
               >);

} // namespace assertions
```

But this didn't work at all in Visual Studio Community 2022 17.7.1. `<see>` seems to be a feature only for document generation. I continued googling about it and finally reached this extension. As workaround, I devised a way to peek the `static_assert` lines in the following steps:

1. Write `static_assert` at the near end of the function.
2. Put a comment `link:v:static_assert` before the definition of the function.
3. When you want to know the type of the returned sequence, right click the identifier of the function.
4. Select "Peek Definition".
5. Click the link in the comment.

```cpp
// For the type of elements, see link:v:static_assert
auto convert_int_vector_to_float_collection(const std::vector<int>& in) {
    auto to_float = [](int elem) {
        return static_cast<float> (elem);
    };
    auto sequence = boost::make_iterator_range(
        boost::make_transform_iterator(in.begin(), to_float),
        boost::make_transform_iterator(in.end(), to_float));
    static_assert (std::is_same_v<decltype (sequence.front()), float>);
    return sequence;
}
```

This didn't work too because of #52. Even after that issue is fixed, it would be nicer if the features I described here are implemented and the code will be like below, so that `static_assert (std::is_same_v<decltype (sequence.front()), float>);` will be shown in the tooltip:

```cpp
// link:v:"Type of elements":"END"
auto convert_int_vector_to_float_collection(const std::vector<int>& in) {
    auto to_float = [](int elem) {
        return static_cast<float> (elem);
    };
    auto sequence = boost::make_iterator_range(
        boost::make_transform_iterator(in.begin(), to_float),
        boost::make_transform_iterator(in.end(), to_float));
    // Type of elements
    static_assert (std::is_same_v<decltype (sequence.front()), float>);
    // END
    return sequence;
}
```

**Comment by mrlacey** [comment]
I'm not entirely sure what you're asking for. Images (mocked up) can be more helpful than a description.

That said, tooltips (Quickinfo) don't have any extension points without completely reimplementing the entire tooltip, which is not something I'm interested in adding to this extension.
It sounds like you're after something very specific and new. Given this, a custom solution is probably more appropriate than trying to retrofit it here, where there is already a lot of complicated interconnected logic.

**Comment by skhrshin** [comment]
> That said, tooltips (Quickinfo) don't have any extension points without completely reimplementing the entire tooltip, which is not something I'm interested in adding to this extension.

I see. Thank you for answering!
