### ISSUE TITLE
Support VS macros

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/CommentLinks#57]
Request from the marketplace:

> 3. Support for VS macros such as $(SolutionDir) etc.

**Comment by mrlacey** [comment]
What to support?

list at: https://stackoverflow.com/a/1519854

**Comment by mrlacey** [comment]
X-Ref #45

**Comment by Ami-Mizuno** [comment]
I will admit this one may not be very useful. However when combined with #56 It would make image paths easier. For example

$(SolutionDir)\MyImages\MyStructFile.png

Of course you could always add a setting to specify a image directory. I think this way is more portable for solutions with multiple projects however.

**Comment by mrlacey** [comment]
Adding support for:

$(ItemPath)
$(ItemDir)
$(ProjectDir)
$(SolutionDir)

**Comment by mrlacey** [comment]
> Adding support for:
> 
> $(ItemPath) $(ItemDir) $(ProjectDir) $(SolutionDir)

These "macros" are supported as part of a file name/path as of version 3.0 (in the marketplace now).
