### ISSUE TITLE
Add predefined jump locations

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/CommentLinks#58]
Request from the marketplace:

> 4. Automatic jumps to predefined areas such as //Link:Top of page.

**Comment by mrlacey** [comment]
Other than `Top` and `Bottom`, what other values (& their locations) make sense?

**Comment by Ami-Mizuno** [comment]
Could perhaps also add a next/previous to help navigate links.

**Comment by mrlacey** [comment]
Thinking about this some more and I'm really not convinced of the value.

I can already easily get to the top (or bottom) of an open document by pressing `Ctrl`+`PgUp` (or `Ctrl`+`PdDn`)
Newly opened documents automatically start at the top, so I don't see a different between opening a document and explicitly opening a document at the top.
If the document is already open in the middle, existing shortcuts provide a simple way to get to the top or bottom of the document.
I can't think of a reason for wanting to open a document at the bottom. If it's to add more to an existing document, why would this be via a comment link?
In terms of wanting to navigate to the "next or "previous" link, why do you want to go to the link? Surely you'd want to go to the section, rather than the actual link. Couldn't you already do this by explicitly linking to the section based on the title as a search term with the link?

**Comment by Ami-Mizuno** [comment]
I think the idea for next/prev is just how i use the links. In my code i typically have a format like

Section A
some stuff

Section B
other stuff

and so on a better example would be say a window header for multiple window types. each window type will have its own messages, structures, notifications, etc.. each one would be a link. this would allow just adding a single link:next: without adding the additional naming etc.. to jump around. really just a small convenience not much of a big deal.

**Comment by mrlacey** [comment]
> I think the idea for next/prev is just how i use the links. In my code i typically have a format like
> 
> Section A some stuff
> 
> Section B other stuff
> 
> and so on a better example would be say a window header for multiple window types. each window type will have its own messages, structures, notifications, etc.. each one would be a link. this would allow just adding a single link:next: without adding the additional naming etc.. to jump around. really just a small convenience not much of a big deal.

This feels like a very specific scenario and I'm not sure how widely applicable/usable it is.
My biggest concern is that I'd look at it and not be certain that I know where "next" will always be.
For code, there's almost certainly better ways for navigating.
For purely documentation, I'm not sold on the value of navigating within a document, especially when there are many other ways of presenting and navigating documentation and I'm not sure that Vs is the best tool for that. 
A dedicated tool/extension in VS for working with specific documentation types may be useful, but this extension was never meant to be that, and I'm not sure it's a direction that it should move towards.

I'm always open to suggestions and keen to learn how other people use tools and the challenges they're encountering.
Please open further issues as you think of them, and happy to discuss them.
It seems that there are opportunities for making a better experience for navigating documentation in VS but it's not something I have time to spend working on at the moment.
