### ISSUE TITLE
CL 2.18 on VS 2022 "Include path to file" when True or False only includes the filename, not the path

### ISSUE THREAD

**Issue by markyoung2u** [mrlacey/CommentLinks#60]
VS 2022: Tools, Options, Comment Links, Include path to file can be true or false but nothing changes.
The help indicates "if set to True, links generated with the context menu will include the path to the file." but it does not work for any of the 3 menu items. If I mark a word, right-click, Comment Links, Copy link to Selection,  I get links without the path?
link:work.txt:errorcodes
link:smMsgs.h:errSelRsv

**Comment by mrlacey** [comment]
Looking at the current code, when this option is enabled, it tries to find the path relative to the project root. If it can't find the project the file is part of then it just outputs the file name.
I guess a better option here would be to include the absolute (full) path if a relative one can't be determined.

Does that sound like a suitable solution?

**Comment by markyoung2u** [comment]
It would be better when "Include path to file" is True that the full path be used regardless of it being found in a project or not. Your code should be simpler, and would work as advertised. Right now it does not work. Doing it halfway is not really a solution, is it?

**Comment by mrlacey** [comment]
The details of why it was originally implemented (#4) the way it was are vague.
Having absolute paths can cause potential issues with shared code bases as the code may be checked out to different paths or even different drives.
Having absolute paths doesn't feel like a perfect solution as one of the original aims for this extension was to help people working with existing code bases that they're not familiar with and such people are more likely to be in a position where absolute paths don't help.

I'm going to do two things:

1. Improve the explanation of the existing functionality.
2. Add a new option to enable the creation of links that always use the absolute path to a file.

**Comment by markyoung2u** [comment]
OK, I understand, Seems fine

**Comment by mrlacey** [comment]
These changes have been release as part of version 3.0 (in the marketplace now).
