### ISSUE TITLE
Folders with '-' seem to have an issue?

### ISSUE THREAD

**Issue by michael-hawker** [mrlacey/CommentLinks#7]
Was trying to link to a resource file:

```cs
/// See Link:Strings/en-us/Resources.resw
```

But get message "unable to find file 'Strings/en'" so it looks like parsing is stopping after '-'?

Trying a different path like:

```cs
/// See Link:Strings/fr/Resources.resw
```

Worked fine.

**Comment by mrlacey** [comment]
This is fixed in version 1.4 (that has just been uploaded to the marketplace)
