### ISSUE TITLE
Support ending a link before the end of line?

### ISSUE THREAD

**Issue by michael-hawker** [mrlacey/CommentLinks#8]
![image](https://user-images.githubusercontent.com/24302614/101557454-e4f0b500-3971-11eb-97ff-7b8fc8f7409f.png)

Thought it was a subtree issue at first, but realized after that it's because I had more text after I had specified the link.

Works:
```
// Reply with task back to so it can be properly awaited link:App.AppService.xaml.cs
```

Doesn't Work:
```
// Reply with task back to link:App.AppService.xaml.cs so they can properly await it 
```

The extra 'so they can properly await it' text was getting picked up. I assume this is because some files have spaces. Should those need quotes around them or something instead?

I also noticed if I put a `#` or `:` at t he end it'd navigate to the file, but it wouldn't jump to the line specified for '#'.

Thoughts?

**Comment by mrlacey** [comment]
Yes, the current behavior is to allow for file and directory names that contain spaces.

Would it be preferable to:
1. require adding quotes (single or double) to the file name to distinguish it
OR
2. Try and detect possible extra words added after the filename based on

1 would be more work for you.
2 would be less work for you but still may not get everything correct. (I'd add tests to try and avoid this but can't guarantee 100% accuracy.)

> I also noticed if I put a # or : at t he end it'd navigate to the file, but it wouldn't jump to the line specified for '#'.

Are you doing `filename.ext#25` or `filename.ext#L25`? It needs the `L` to know it's a line number

Can you clarify what you're doing with the colon at the end? Or provide an example?

**Comment by michael-hawker** [comment]
@mrlacey I was doing the `#L25` as you would normally, but it seems like the number parser was getting tripped up by the extra words as well, but it'd then at least recognize the earlier file part and go to the file, just not the line number.

I was testing the ':' similarly for the text fragment searching, but I believe then it was trying to search for all the text as well.

Would it make sense to try and support both mechanisms? i.e. try and be greedy and detect the right file name based on context, but also support wrapping everything in quotes to be explicit about the link contents?

So this could work:

`// Reply with task back to link:App.AppService.xaml.cs so they can properly await it `

But also this:

`// Reply with task back to link:"App.AppService.xaml.cs:Some search text" so they can properly await it`

**Comment by mrlacey** [comment]
```
Developer: Would you like option A or option B
Client: Both!
```

**Version 1.5 has now been submitted to the marketplace and should give you everything you want.**

If you find it doesn't handle a specific example, please provide the text of the line as an example.
(I've added test cases for 62 scenarios but may have still missed some.)

**Comment by mrlacey** [comment]
closing as no further details so assuming that the latest version addresses the original concerns raised in this issue.
If you find any scenarios that are not handled correctly, please open a new issue
